#!/usr/bin/env python3
"""
TROS PRO — Multi-platform KOL Scraper (TikTok + Facebook) via yt-dlp.
Scrapes views/likes/shares/comments/saves/followers from each post link.
Usage: python3 scripts/scraper.py [output_json]
"""
import json, sys, subprocess, time, random

# KOLs that yt-dlp cannot fetch (age-restricted / login / Facebook private).
# Paste the latest numbers you read by eye; they override the auto-scrape.
MANUAL_OVERRIDE = {
    # 'handle': {'views':0,'likes':0,'shares':0,'comments':0,'saves':0,'followers':0},
}

# handle -> {url, platform}  (generated by kol-dashboard-generator)
KOL_LINKS = {
    "bass__inmeesub": {
        "url": "https://vt.tiktok.com/ZSXgmUfA8/",
        "platform": "TikTok"
    },
    "kuanpuantiew": {
        "url": "https://vt.tiktok.com/ZSXgqSFbs/",
        "platform": "TikTok"
    },
    "juno55555": {
        "url": "https://vt.tiktok.com/ZSXgpUoF4/",
        "platform": "TikTok"
    },
    "pluemwattanathon": {
        "url": "https://vt.tiktok.com/ZSXgCbosJ/",
        "platform": "TikTok"
    },
    "bee112711": {
        "url": "https://vt.tiktok.com/ZSXgmXbkW/",
        "platform": "TikTok"
    },
    "kunofficial29": {
        "url": "https://vt.tiktok.com/ZSXqv1ytm/",
        "platform": "TikTok"
    },
    "pakkaput17": {
        "url": "https://vt.tiktok.com/ZSXb9cbeX/",
        "platform": "TikTok"
    },
    "benmar_98": {
        "url": "https://vt.tiktok.com/ZSXg96w3m/",
        "platform": "TikTok"
    },
    "sapol_mu_": {
        "url": "https://vt.tiktok.com/ZSXguN6Gr/",
        "platform": "TikTok"
    },
    "folk.rt": {
        "url": "https://vt.tiktok.com/ZSXggLvfp/",
        "platform": "TikTok"
    },
    "homchuy": {
        "url": "https://vt.tiktok.com/ZSXgp9fcv/",
        "platform": "TikTok"
    },
    "pangpon.thatpong": {
        "url": "https://vt.tiktok.com/ZSXgwqy9u/",
        "platform": "TikTok"
    },
    "pattarapon_mike": {
        "url": "https://vt.tiktok.com/ZSXgQGLjv/",
        "platform": "TikTok"
    },
    "mac5869": {
        "url": "https://vt.tiktok.com/ZSXgqvweV/",
        "platform": "TikTok"
    },
    "ig_earthalert24": {
        "url": "https://vt.tiktok.com/ZSXgm3eLV/",
        "platform": "TikTok"
    },
    "i.thinnajohn": {
        "url": "https://vt.tiktok.com/ZSXbPDroy/",
        "platform": "TikTok"
    },
    "artchanathip.ppppp": {
        "url": "https://vt.tiktok.com/ZSXgxGT7k/",
        "platform": "TikTok"
    }
}


KOL_LINKS["wecanchoose"]={"url":"https://www.facebook.com/wecanchoose/posts/1574463894474621","platform":"Facebook"}
MANUAL_OVERRIDE["wecanchoose"]={"views":4460483,"likes":0,"shares":0,"comments":0,"saves":0,"followers":3000000}

import re, urllib.request
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"

def _n(html,key):
    m=re.search(key+r'"?\s*:\s*"?(\d+)',html)
    return int(m.group(1)) if m else 0

def scrape(url, platform):
    try:
        req=urllib.request.Request(url,headers={"User-Agent":UA,"Accept-Language":"en-US,en;q=0.9"})
        html=urllib.request.urlopen(req,timeout=30).read().decode("utf-8","ignore")
    except Exception as e:
        print("    fetch error:",str(e)[:140]); return None
    if "playCount" not in html:
        print("    no data (blocked?) len",len(html)); return None
    return {"url":url,"platform":platform,"views":_n(html,"playCount"),
            "likes":_n(html,"diggCount"),"comments":_n(html,"commentCount"),
            "shares":_n(html,"shareCount"),"saves":_n(html,"collectCount"),
            "followers":_n(html,"followerCount")}


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else 'scrape_results.json'
    active = {k:v for k,v in KOL_LINKS.items() if v.get('url','').strip()}
    results = {}
    print(f"Scraping {len(active)} post(s)...")
    for handle, info in active.items():
        if handle in MANUAL_OVERRIDE:
            results[handle] = {**MANUAL_OVERRIDE[handle], 'url': info['url'], 'platform': info['platform']}
            print(f"  @{handle} — manual override"); continue
        print(f"  @{handle} [{info['platform']}] ...")
        data = scrape(info['url'], info['platform'])
        if data:
            results[handle] = data
            print(f"    views {data['views']:,} | likes {data['likes']:,} | "
                  f"cmt {data['comments']:,} | shr {data['shares']:,} | save {data['saves']:,}")
        else:
            print(f"    FAILED @{handle}")
        time.sleep(random.uniform(0.5, 1.5))
    with open(out, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    print(f"\nSaved {len(results)}/{len(active)} -> {out}")


if __name__ == '__main__':
    main()
